---
- name: GitOps Namespace
  kubernetes.core.k8s:
    name: openshift-gitops-operator
    api_version: v1
    kind: Namespace
    state: present

- name: GitOps Operator Group
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: openshift-gitops-operator
        namespace: openshift-gitops-operator
      spec:
        upgradeStrategy: Default

- name: GitOps Subscription
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: openshift-gitops-operator
        namespace: openshift-gitops-operator
      spec:
        channel: latest
        name: openshift-gitops-operator
        source: redhat-operators
        sourceNamespace: openshfit-marketplace
        installPlanApproval: Automatic

- name: Wait for argocd object
  kubernetes.core.k8s_info:
    state: present
    apiVersion: argoproj.io/v1beta1
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
  retries: 10
  delay: 10
